name: build-mac
on:
  push:
    paths:
      - 'src/**'
      - 'libs/**'
      - 'cmake/**'
      - '.github/**'
      - '**/CMakeLists.txt'

jobs:
  build-matrix:
      runs-on: ${{ matrix.os }}
      strategy:
        fail-fast: false
        matrix:
          os:
            - macos-latest
          compiler:
          - gcc
          - llvm
          - clang
          exclude:
          # macos with gcc does not work with gcc for some reason (works with llvm and clang) so just ignore for now.
            - os: "macos-latest"
              compiler: gcc
      steps:
        - name: Get submodules
          uses: actions/checkout@v3
          with:
            submodules: recursive
      
        # - name: Cache libraries

        - name: Setup C++ with ${{ matrix.compiler }}
          uses: aminya/setup-cpp@v1
          with:
            compiler: ${{ matrix.compiler }}

        - name: Get Cmake and Ninja
          uses: lukka/get-cmake@latest

        - name: Configure sed for macOS
          shell: bash
          run: |
            brew install gnu-sed && echo "export PATH=\"/usr/local/opt/gnu-sed/libexec/gnubin:\$PATH\"" >> $GITHUB_PATH && source $GITHUB_PATH && which sed

        - name: Configure Vulkan SDK
          uses: ./.github/setup-vulkan-sdk
          with:
            vulkan-query-version: latest
            vulkan-components: Vulkan-Loader, shaderc
            vulkan-use-cache: false

        - name: Run CMake + Ninja
          uses: lukka/run-cmake@v10
          with:
            cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
            configurePreset: 'ninja'
            buildPreset: 'ninja'