name: build-windows
on:
  push:
    paths:
      - 'src/**'
      - 'libs/**'
      - 'cmake/**'
      - '.github/**'
      - '**/CMakeLists.txt'
jobs:
  build-matrix:
      runs-on: ${{ matrix.os }}
      strategy:
        fail-fast: false
        matrix:
          os: windows-latest
          compiler: msvc
          build-preset: VisualStudio
          build-config:
             - Debug
             - Release
      steps:
        - name: Get submodules
          uses: actions/checkout@v3
          with:
            submodules: recursive      

        - name: Setup C++ with ${{ matrix.compiler }}
          uses: aminya/setup-cpp@v1
          with:
            compiler: ${{ matrix.compiler }}

        - name: Get Cmake and Ninja
          uses: lukka/get-cmake@latest
        
        - name: Configure Vulkan SDK
          uses: ./.github/actions/setup-vulkan-sdk
          with:
            vulkan-query-version: latest
            vulkan-components: Vulkan-Loader, shaderc
            vulkan-use-cache: on
        
        - name: Run CMake + Ninja
          uses: lukka/run-cmake@v10
          with:
            cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
            configurePreset: '${{matrix.build-preset}}_${{matrix.build-config}}'
            buildPreset: '${{matrix.build-preset}}_${{matrix.build-config}}'