name: build-windows
on:
  push:
    paths:
      - 'src/**'
      - 'libs/**'
      - 'cmake/**'
      - '.github/**'
      - '**/CMakeLists.txt'
    branches: [main]

jobs:
  build-matrix:
      runs-on: ${{ matrix.os }}
      strategy:
        fail-fast: false
        matrix:
          os: 
            - windows-latest
          compiler: 
            - msvc
          build-preset:
            - VisualStudio
            - Ninja
          build-config:
            - Debug
            - Release
      steps:
        - uses: actions/checkout@v3
          with:
            submodules: recursive      

        - uses: aminya/setup-cpp@v1
          with:
            compiler: ${{ matrix.compiler }}

        - uses: lukka/get-cmake@latest
        
        - uses: ./.github/actions/setup-vulkan-sdk
          with:
            vulkan-query-version: latest
            vulkan-components: Vulkan-Loader, shaderc
            vulkan-use-cache: false
            build-config: ${{ matrix.build-config }}
        
        - uses: lukka/run-cmake@v10
          with:
            cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
            configurePreset: '${{matrix.build-preset}}_${{matrix.build-config}}'
            buildPreset: '${{matrix.build-preset}}_${{matrix.build-config}}'