name: build-project
on: [push]
jobs:
  build-matrix:
      runs-on: ${{ matrix.os }}
      strategy:
        fail-fast: false
        matrix:
          os:
            - ubuntu-20.04
            - macos-11
          compiler:
          - gcc
          - clang
          include:
            - os: "windows-latest"
              compiler: "msvc"
      steps:
        - uses: actions/checkout@v2
          with:
            submodules: recursive
        - name: Setup C++ with 
          uses: aminya/setup-cpp@v1
          with:
            compiler: ${{ matrix.compiler }}
            cmake: true
            ninja: true
            make: true
        - name: Prepare Vulkan SDK
          uses: humbletim/setup-vulkan-sdk@v1.2.0
          with:
            vulkan-query-version: latest
            vulkan-components: Vulkan-Headers, Vulkan-Loader, Glslang
            vulkan-use-cache: true
        - name: Compile
          env:
            CC: ${{ matrix.compiler }}
            CXX: ${{ matrix.compiler }}
          run: cmake -S . -B build && cmake --build build